# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Nov  8 22:14:50 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(618, 457)
        MainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 26, 618, 408))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeCluster = QtGui.QTreeWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeCluster.sizePolicy().hasHeightForWidth())
        self.treeCluster.setSizePolicy(sizePolicy)
        self.treeCluster.setMinimumSize(QtCore.QSize(150, 0))
        self.treeCluster.setMaximumSize(QtCore.QSize(200, 16777215))
        self.treeCluster.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.treeCluster.setObjectName("treeCluster")
        self.horizontalLayout.addWidget(self.treeCluster)
        self.tabsMain = QtGui.QTabWidget(self.centralwidget)
        self.tabsMain.setMinimumSize(QtCore.QSize(325, 0))
        self.tabsMain.setObjectName("tabsMain")
        self.MTasks = QtGui.QWidget()
        self.MTasks.setGeometry(QtCore.QRect(0, 0, 390, 362))
        self.MTasks.setObjectName("MTasks")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.MTasks)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbClearKey = QtGui.QGroupBox(self.MTasks)
        self.gbClearKey.setFlat(False)
        self.gbClearKey.setObjectName("gbClearKey")
        self.gridLayout_2 = QtGui.QGridLayout(self.gbClearKey)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblCacheKeys = QtGui.QLabel(self.gbClearKey)
        self.lblCacheKeys.setObjectName("lblCacheKeys")
        self.gridLayout_2.addWidget(self.lblCacheKeys, 0, 0, 1, 1)
        self.txtCacheKeys = QtGui.QLineEdit(self.gbClearKey)
        self.txtCacheKeys.setObjectName("txtCacheKeys")
        self.gridLayout_2.addWidget(self.txtCacheKeys, 0, 1, 1, 1)
        self.btnCacheKeys = QtGui.QPushButton(self.gbClearKey)
        self.btnCacheKeys.setObjectName("btnCacheKeys")
        self.gridLayout_2.addWidget(self.btnCacheKeys, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbClearKey)
        self.gbTasks = QtGui.QGroupBox(self.MTasks)
        self.gbTasks.setObjectName("gbTasks")
        self.gridLayout = QtGui.QGridLayout(self.gbTasks)
        self.gridLayout.setObjectName("gridLayout")
        self.btnFlushCache = QtGui.QPushButton(self.gbTasks)
        self.btnFlushCache.setObjectName("btnFlushCache")
        self.gridLayout.addWidget(self.btnFlushCache, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.gbTasks)
        self.tabsMain.addTab(self.MTasks, "")
        self.SKInfo = QtGui.QWidget()
        self.SKInfo.setGeometry(QtCore.QRect(0, 0, 390, 362))
        self.SKInfo.setObjectName("SKInfo")
        self.tabsMain.addTab(self.SKInfo, "")
        self.Stats = QtGui.QWidget()
        self.Stats.setGeometry(QtCore.QRect(0, 0, 390, 362))
        self.Stats.setObjectName("Stats")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.Stats)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabsStats = QtGui.QTabWidget(self.Stats)
        self.tabsStats.setObjectName("tabsStats")
        self.tab = QtGui.QWidget()
        self.tab.setGeometry(QtCore.QRect(0, 0, 368, 316))
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gbTotals = QtGui.QGroupBox(self.tab)
        self.gbTotals.setObjectName("gbTotals")
        self.gridLayout_3 = QtGui.QGridLayout(self.gbTotals)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblCurrentItemsTxt = QtGui.QLabel(self.gbTotals)
        self.lblCurrentItemsTxt.setObjectName("lblCurrentItemsTxt")
        self.gridLayout_3.addWidget(self.lblCurrentItemsTxt, 0, 0, 1, 1)
        self.lblCurrentItems = QtGui.QLabel(self.gbTotals)
        self.lblCurrentItems.setObjectName("lblCurrentItems")
        self.gridLayout_3.addWidget(self.lblCurrentItems, 0, 1, 1, 1)
        self.lblHitsTxt = QtGui.QLabel(self.gbTotals)
        self.lblHitsTxt.setObjectName("lblHitsTxt")
        self.gridLayout_3.addWidget(self.lblHitsTxt, 1, 0, 1, 1)
        self.lblHits = QtGui.QLabel(self.gbTotals)
        self.lblHits.setObjectName("lblHits")
        self.gridLayout_3.addWidget(self.lblHits, 1, 1, 1, 1)
        self.lblMissesTxt = QtGui.QLabel(self.gbTotals)
        self.lblMissesTxt.setObjectName("lblMissesTxt")
        self.gridLayout_3.addWidget(self.lblMissesTxt, 2, 0, 1, 1)
        self.lblMisses = QtGui.QLabel(self.gbTotals)
        self.lblMisses.setObjectName("lblMisses")
        self.gridLayout_3.addWidget(self.lblMisses, 2, 1, 1, 1)
        self.lblFreeTxt = QtGui.QLabel(self.gbTotals)
        self.lblFreeTxt.setObjectName("lblFreeTxt")
        self.gridLayout_3.addWidget(self.lblFreeTxt, 3, 0, 1, 1)
        self.lblFree = QtGui.QLabel(self.gbTotals)
        self.lblFree.setObjectName("lblFree")
        self.gridLayout_3.addWidget(self.lblFree, 3, 1, 1, 1)
        self.lblUsedTxt = QtGui.QLabel(self.gbTotals)
        self.lblUsedTxt.setObjectName("lblUsedTxt")
        self.gridLayout_3.addWidget(self.lblUsedTxt, 4, 0, 1, 1)
        self.lblUsed = QtGui.QLabel(self.gbTotals)
        self.lblUsed.setObjectName("lblUsed")
        self.gridLayout_3.addWidget(self.lblUsed, 4, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.gbTotals)
        self.gbRates = QtGui.QGroupBox(self.tab)
        self.gbRates.setObjectName("gbRates")
        self.gridLayout_4 = QtGui.QGridLayout(self.gbRates)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblRequestRateTxt = QtGui.QLabel(self.gbRates)
        self.lblRequestRateTxt.setObjectName("lblRequestRateTxt")
        self.gridLayout_4.addWidget(self.lblRequestRateTxt, 0, 0, 1, 1)
        self.lblRequestRate = QtGui.QLabel(self.gbRates)
        self.lblRequestRate.setObjectName("lblRequestRate")
        self.gridLayout_4.addWidget(self.lblRequestRate, 0, 1, 1, 1)
        self.lblHitRateTxt = QtGui.QLabel(self.gbRates)
        self.lblHitRateTxt.setObjectName("lblHitRateTxt")
        self.gridLayout_4.addWidget(self.lblHitRateTxt, 1, 0, 1, 1)
        self.lblHitRate = QtGui.QLabel(self.gbRates)
        self.lblHitRate.setObjectName("lblHitRate")
        self.gridLayout_4.addWidget(self.lblHitRate, 1, 1, 1, 1)
        self.lblMissRateTxt = QtGui.QLabel(self.gbRates)
        self.lblMissRateTxt.setObjectName("lblMissRateTxt")
        self.gridLayout_4.addWidget(self.lblMissRateTxt, 2, 0, 1, 1)
        self.lblMissRate = QtGui.QLabel(self.gbRates)
        self.lblMissRate.setObjectName("lblMissRate")
        self.gridLayout_4.addWidget(self.lblMissRate, 2, 1, 1, 1)
        self.lblSetRateTxt = QtGui.QLabel(self.gbRates)
        self.lblSetRateTxt.setObjectName("lblSetRateTxt")
        self.gridLayout_4.addWidget(self.lblSetRateTxt, 3, 0, 1, 1)
        self.lblSetRate = QtGui.QLabel(self.gbRates)
        self.lblSetRate.setObjectName("lblSetRate")
        self.gridLayout_4.addWidget(self.lblSetRate, 3, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.gbRates)
        self.tabsStats.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setGeometry(QtCore.QRect(0, 0, 368, 316))
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtGui.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 331, 492))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblCacheUsage = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblCacheUsage.setObjectName("lblCacheUsage")
        self.verticalLayout.addWidget(self.lblCacheUsage)
        self.graphCacheUsage = QtGui.QGraphicsView(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphCacheUsage.sizePolicy().hasHeightForWidth())
        self.graphCacheUsage.setSizePolicy(sizePolicy)
        self.graphCacheUsage.setMinimumSize(QtCore.QSize(250, 210))
        self.graphCacheUsage.setMaximumSize(QtCore.QSize(250, 210))
        self.graphCacheUsage.setBaseSize(QtCore.QSize(250, 210))
        self.graphCacheUsage.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphCacheUsage.setFrameShadow(QtGui.QFrame.Sunken)
        self.graphCacheUsage.setObjectName("graphCacheUsage")
        self.verticalLayout.addWidget(self.graphCacheUsage)
        self.lblHitsMisses = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lblHitsMisses.setObjectName("lblHitsMisses")
        self.verticalLayout.addWidget(self.lblHitsMisses)
        self.graphHitMiss = QtGui.QGraphicsView(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphHitMiss.sizePolicy().hasHeightForWidth())
        self.graphHitMiss.setSizePolicy(sizePolicy)
        self.graphHitMiss.setMinimumSize(QtCore.QSize(250, 210))
        self.graphHitMiss.setMaximumSize(QtCore.QSize(250, 210))
        self.graphHitMiss.setFrameShape(QtGui.QFrame.NoFrame)
        self.graphHitMiss.setObjectName("graphHitMiss")
        self.verticalLayout.addWidget(self.graphHitMiss)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.tabsStats.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabsStats.addTab(self.tab_3, "")
        self.horizontalLayout_2.addWidget(self.tabsStats)
        self.tabsMain.addTab(self.Stats, "")
        self.horizontalLayout.addWidget(self.tabsMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 618, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Servers = QtGui.QMenu(self.menubar)
        self.menu_Servers.setObjectName("menu_Servers")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0, 434, 618, 23))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAddServer = QtGui.QAction(MainWindow)
        self.actionAddServer.setObjectName("actionAddServer")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAddCluster = QtGui.QAction(MainWindow)
        self.actionAddCluster.setObjectName("actionAddCluster")
        self.actionTest_Sub_Item = QtGui.QAction(MainWindow)
        self.actionTest_Sub_Item.setObjectName("actionTest_Sub_Item")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menu_Servers.addAction(self.actionAddServer)
        self.menu_Servers.addAction(self.actionAddCluster)
        self.menu_Servers.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Servers.menuAction())

        self.retranslateUi(MainWindow)
        self.tabsMain.setCurrentIndex(2)
        self.tabsStats.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.treeCluster.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Clusters", None, QtGui.QApplication.UnicodeUTF8))
        self.gbClearKey.setTitle(QtGui.QApplication.translate("MainWindow", "Delete Key(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCacheKeys.setText(QtGui.QApplication.translate("MainWindow", "Cache Key(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.txtCacheKeys.setToolTip(QtGui.QApplication.translate("MainWindow", "Seperate Keys with \';\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCacheKeys.setText(QtGui.QApplication.translate("MainWindow", "Delete Key(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.gbTasks.setTitle(QtGui.QApplication.translate("MainWindow", "Server Admin Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFlushCache.setToolTip(QtGui.QApplication.translate("MainWindow", "Flush Keys from All Servers in Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFlushCache.setText(QtGui.QApplication.translate("MainWindow", "Flush Cache Keys", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.MTasks), QtGui.QApplication.translate("MainWindow", "Management Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabToolTip(self.tabsMain.indexOf(self.MTasks), QtGui.QApplication.translate("MainWindow", "Cluster Management Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.SKInfo), QtGui.QApplication.translate("MainWindow", "Slab && Key Info", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabToolTip(self.tabsMain.indexOf(self.SKInfo), QtGui.QApplication.translate("MainWindow", "Slabs, Keys, & Values", None, QtGui.QApplication.UnicodeUTF8))
        self.gbTotals.setTitle(QtGui.QApplication.translate("MainWindow", "Totals", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCurrentItemsTxt.setText(QtGui.QApplication.translate("MainWindow", "Number of Items:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCurrentItems.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHitsTxt.setText(QtGui.QApplication.translate("MainWindow", "Hits:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHits.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMissesTxt.setText(QtGui.QApplication.translate("MainWindow", "Misses:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMisses.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFreeTxt.setText(QtGui.QApplication.translate("MainWindow", "Free Space:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFree.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsedTxt.setText(QtGui.QApplication.translate("MainWindow", "Used Space:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUsed.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.gbRates.setTitle(QtGui.QApplication.translate("MainWindow", "Cache Rates", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRequestRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Request Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRequestRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHitRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Hit Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHitRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMissRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Miss Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMissRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSetRateTxt.setText(QtGui.QApplication.translate("MainWindow", "Set Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSetRate.setText(QtGui.QApplication.translate("MainWindow", "n/a", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsStats.setTabText(self.tabsStats.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Cache Info", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCacheUsage.setText(QtGui.QApplication.translate("MainWindow", "Cache Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHitsMisses.setText(QtGui.QApplication.translate("MainWindow", "Hits and Misses", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsStats.setTabText(self.tabsStats.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Diagrams", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsStats.setTabText(self.tabsStats.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Server Information", None, QtGui.QApplication.UnicodeUTF8))
        self.tabsMain.setTabText(self.tabsMain.indexOf(self.Stats), QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Servers.setTitle(QtGui.QApplication.translate("MainWindow", "&Servers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddServer.setText(QtGui.QApplication.translate("MainWindow", "&Add Server", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Sa&ve", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddCluster.setText(QtGui.QApplication.translate("MainWindow", "Add &Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTest_Sub_Item.setText(QtGui.QApplication.translate("MainWindow", "Test Sub Item", None, QtGui.QApplication.UnicodeUTF8))

